apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bx7tcnf24-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bx7tcnf24-dotnet-basic-gitops